version: "3.7"
services:
  postgres:
    image: postgres
    restart: always
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "password"
    networks:
      - develop
  web:
    restart: always
    build: .
    ports:
      - "8081:8081"
    expose:
      - "8081"
    networks:
      - develop
    depends_on:
      - postgres
  wiremock:
    image: rodolpheche/wiremock
    restart: always
    hostname: wiremock
    ports:
      - "8080:8080"
      - "8443:8443"
    expose:
      - "8080"
    networks:
      - develop
    volumes:
      - ./wiremock/weather:/home/wiremock
networks:
  develop:
    driver: bridge  